apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: matter-server
resources:
  - namespace.yaml
  - cr.multus.yaml
  - service.yaml
  - pv.yaml
  - pvc.yaml
  - statefulset.yaml
labels:
  - pairs:
      app.kubernetes.io/name: "matter-server"
    includeSelectors: true
    includeTemplates: true
