apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - daemonset.yaml
labels:
  - pairs:
      app: cni-plugins-installer
    includeSelectors: true
    includeTemplates: true
