apiVersion: apps/v1
kind: Deployment
metadata:
  name: wyoming-whisper
spec:
  replicas: 1
  selector: {}
  template:
    spec:
      containers:
        - name: whisper
          image: rhasspy/wyoming-whisper:latest
          args:
            - --model
            - tiny-int8
            - --language
            - de
          ports:
            - name: whisper
              containerPort: 10300
          volumeMounts:
            - name: whisper-data
              mountPath: /data
      volumes:
        - name: whisper-data
          persistentVolumeClaim:
            claimName: wyoming-whisper-data