apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.redis.yaml
  - deployment.yaml
  - service.yaml
labels:
  - pairs:
      app.kubernetes.io/component: broker
    includeTemplates: true
    includeSelectors: true
