apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      server: 10.0.0.21
      share: /mnt/data/csi/named
      subdir: music
    volumeHandle: 10.0.0.21#mnt/data/csi/named#grafana##
  mountOptions:
    - nfsvers=4.1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-named
  volumeMode: Filesystem
