apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:JUUErS4=,iv:rc7PjbKgGfE4z1Hxldb8ltGm38P58fS9TiL62nXJRdM=,tag:ER3/+aLKTWFCAAxSHoiTzg==,type:str]
    password: ENC[AES256_GCM,data:INTotkLVGqkbpS4qVnIN6hg6Lfw=,iv:l5GWl42vdlNX7fDKesk9pHGaCXj4anB7V5lxe6gqbIc=,tag:bA/aI8yZpFmp5BT6hFXYxw==,type:str]
sops:
    age:
        - recipient: age1cl4m8gptnm0vm4g53x05fnn2r82u8hvdatkx07uheky4z7q7ef7sukrmwl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySk5MZVUzY3ZFY2FnaE8w
            TWpMVDZRZnNLOFhKMldwdTY2ZDJRc2c0M1RJCm1ZQVcvS1Z1MUVmU1JvaWFaSDhp
            ZHJvZG5EWlJDc3hUZnVBendLd25jTDAKLS0tIHJJRkVBZmRQemZhN21BSGdBN1k0
            THJmZUJBODFiSCtpOFE2QmIrd3FySlkKpMQkpAbVYzWRA/aB25NnZ9yM1vKIHuoS
            DzRdiVHE0j9ICNlPTl579YHgDD23KNxd56AnJEeke4KqVKbVHR/7Xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T18:26:49Z"
    mac: ENC[AES256_GCM,data:Re2kcEHxdzOIf9ie8MFyFVNVtpRkk2DhAbijbrT1slvyRIjfX73FBIALjF84bGd4ylqy84vA1WT1iM1Bplj36BQQGPSUw9Qlfdq/8SSTDz+wpXXkCgLBChoOUVSdoDpruRVGy7RtxvHvYYrGyjIXsgBtjNdxfHNtXyh1kq0oDMs=,iv:VqZqeZMHXvWeXSASqv9+KLeShTNN4g/nJO9QxwXWhno=,tag:CPn3LNvq3Oj9OpAdFD/vOw==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.10.2
