apiVersion: v1
kind: Secret
metadata:
    name: ddns-updater-config
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:iLwU6HRyT+dL77MOm6YOiclWFL2s9b0Citqvgnd88pTqCP9sE2pU3GC2Ba/nv6EYoZOUDUVGOftA6kSAN5kYfrSLSRaKTAxx6pboWIaq13DCpIEuFDtLpby/TZKQ7JtIrcnPPTSp+TAN2lStqkDweu9I4BFTkb6s5tduRkDbmPN2UonotpMFNJ2c30H/3mq1HjAAtH/BCZlvjtrGF+P1m2RKC/WzcY3rWvdiL72xeox9l3GxzboN5IcSGd+zx5KEdFC/i3n00nsR79hUrSNifSZh9KKYwbp+68KZF3a6TNW8ILlU5KW73EIk/hz0p32UcPvT/8IB67nrw1jpeRPJj7roA3+LSD1Tc5fY,iv:OqIhRa5reNICfme4BbK2aZEl8emptwRYT+FVxj1uvVc=,tag:lG1r4s9v7AyKKrYHF9obQA==,type:str]
sops:
    age:
        - recipient: age1cl4m8gptnm0vm4g53x05fnn2r82u8hvdatkx07uheky4z7q7ef7sukrmwl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWngvNkRscm9SeTJJRGFn
            YStTYkNoRklYYXlLMkMwM0JsNXEyaERCWGkwCjg4TW50ZTNWcVZiUldra3F4K0gv
            TWpRMEswZDBXbmxXZVlFSGk3YXhPTkUKLS0tIENMSUhFU1dKcVBqUFJqcFJVT1FE
            MVJjaHU0SkhLdzhzUWQxZGkvUmd5ZUkKtxXJX3UgKbmZCn7vs+JnkcwjUKtp9S1S
            jR2RellO20sxDCSjcJBr0iNcXFAmccCsTABpFwidGLpWD75o15qA2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T22:22:28Z"
    mac: ENC[AES256_GCM,data:BAIJlr2ooekAgYWtdcSxNhqOTnit84HABDynC7FrVvPH+PtHL3+wQRtRzg+LTQne0twJoQQoc2W0ecUQG7WQWA/B9nGn9pO9c9Xsy0afy3AAx5MUTRjlhcNXSvLBC6fhqZW+uGMEtmdd+uUfOFj4P31E9RdF/gMvN6lJJbb4DKM=,iv:Wy9YwGx1GoGqVxmbs9QAS1J7IvM8jW5cMRvoX1833pA=,tag:wEgvNrJmT4pRjlY3yX11qA==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.10.2
