apiVersion: v1
kind: Secret
metadata:
    name: ddns-updater-config
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:dtwB7Vw6QN01IwuPLFPeBZBiBdc7g1ztZ2/olZax/LmhTGEH1idgS+ah2o9XCUeuE4q3HQvTvcG5vbulzyMGibqlb7A9qnPDOGz4L47jvuHVddWwAiMJ/9s0rtv8swdq6ozwk0R5BhUe4wtFD4sfhNP4+8++M0hidLrRyydmHb/iflT1fOx9zzFOZHSLf65kTMycC40Mt2lSnuJutv/tWazPKq5gONrhUB0zkxvI81Wu8oDpQmt1GkM1osox83yjLf1/m4mvwsrJLUti2JyuW//i95OKKiBIK1toj+k0/lLJzH1uEOHNOOchElgBwZ9I+TDB70Wc6k7EcMo19NJtSnZIGIlNHVm00xE=,iv:luz6wNxsli/nzupsN7xQTPsgEsktKvP/sWfiGmGNvM8=,tag:QbV5+WpgC+0elv6ND+AO1g==,type:str]
sops:
    age:
        - recipient: age1cl4m8gptnm0vm4g53x05fnn2r82u8hvdatkx07uheky4z7q7ef7sukrmwl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTM3YvQ3hWOGx5Mks4WTBQ
            WWF6a2JGL2UwU0dUaFMxaWFMOUJJRHR5WGlRCnlvcW5wK2lHNllPd0E2MWVxNFM0
            TWZmYUdGakwrcUNlNDZSZnBIM3A5cUEKLS0tIFZLbzdvVVdTR05wUEdpbE1uYjgy
            WWNxZVZBVjRPVXRyS05HY2VOL0UyNzAKAeF7umrW8TKc3u0xZQadYXWIT3SkeolT
            stOeslqEHK+GvGWF70AlQsfFWIVetAfMi70Ia26FfB4lSFkUrl6+yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T22:18:38Z"
    mac: ENC[AES256_GCM,data:PYJo+kPASD7NjLc6EINa13pRFSMj8qNOgsxOyYW1QvASyIypAiWw94PBlLzS52oAPaNUSThPaIdyh6oT9z86w6U6HJ+N6jjZOejkI+2UmQdh1iZ6eTAsPet//O7/pNkYuK5EWuz4SDl4fRqmhrN7GQidb5StnArFV1lPSK85Ag4=,iv:wAKpc30ogdg6rqT4cmxgOHzGT5g21X8Ju9i6HsNrMG0=,tag:uJIuaVPn7UHhQECzm+31+Q==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.10.2
