apiVersion: v1
kind: ConfigMap
metadata:
  name: speedtest-tracker-env
data:
  APP_TIMEZONE: "Europe/Berlin"
  DISPLAY_TIMEZONE: "Europe/Berlin"
  DATETIME_FORMAT: "d.m.y"
  PUBLIC_DASHBOARD: "true"
  # DB
  DB_CONNECTIONS: "pgsql"
  DB_HOST: "postgres-cluster"
  DB_PORT: "5432"
  # Speedtest
  SPEEDTEST_SCHEDULE: "*/15 * * * *"
  # See https://c.speedtest.net/speedtest-servers-static.php
  SPEEDTEST_SERVERS: "38032,20507,30907"
  SPEEDTEST_CHECKINTERNET_URL: "google.com"


