apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: speedtest
resources:
  - namespace.yaml
  - ../controllers/cloudnative-pg/cluster
  - configmap.env.yaml
  #- deployment.yaml
  #- service.yaml
labels:
  - pairs:
      app.kubernetes.io/name: "speedtest-tracker"
    includeSelectors: true
    includeTemplates: true
