apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: speedtest
resources:
  - namespace.yaml
  - ../controllers/cloudnative-pg/cluster
  - configmap.env.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
labels:
  - pairs:
      app.kubernetes.io/name: "speedtest-tracker"
    includeSelectors: true
    includeTemplates: true
patches:
  - target:
      kind: HelmRelease
      name: postgres-cluster
    patch: |
      - op: replace
        path: /spec/values/cluster/storage/storageClass
        value: "nfs-retain"
