apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open-thread-border-router
resources:
  - namespace.yaml
  - cr.multus.yaml
  - pv.yaml
  - pvc.yaml
  #- statefulset.yaml
labels:
  - pairs:
      app.kubernetes.io/name: "otbr"
    includeSelectors: true
    includeTemplates: true
