apiVersion: v1
kind: ConfigMap
metadata:
  name: config-git-sync
data:
  GITSYNC_REPO: "https://github.com/noahlehmann/home-assistant.git"
  GITSYNC_REF: "main"
  GITSYNC_ROOT: "/config"
  GITSYNC_DEPTH: "1"
