apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
resources:
  - namespace.yaml
  - configmap.env.yaml
  - configmap.git.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
labels:
  - pairs:
      app.kubernetes.io/name: "home-assistant"
    includeSelectors: true
    includeTemplates: true
