apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
resources:
  - namespace.yaml
  - cr.multus.yaml
  - configmap.env.yaml
  - configmap.git.yaml
  - secret.metrics.yaml
  - pv.yaml
  - pvc.yaml
  - service.yaml
  - statefulset.yaml
  - service-monitor.yaml
  - ingress.yaml
labels:
  - pairs:
      app.kubernetes.io/name: "home-assistant"
    includeSelectors: true
    includeTemplates: true
