apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: music-assistant
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
spec:
  ingressClassName: dmz-ingress
  tls:
    - hosts:
        - music-assistant.golocal.dev
      secretName: music-assistant-tls
  rules:
    - host: music-assistant.golocal.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: music-assistant
                port:
                  name: web
