apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: music-assistant
resources:
  - namespace.yaml
  - cr.multus.yaml
  - pv.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
labels:
  - pairs:
      app.kubernetes.io/name: "music-assistant"
    includeSelectors: true
    includeTemplates: true
