apiVersion: v1
kind: Service
metadata:
  name: music-assistant
spec:
  type: NodePort
  ports:
    - name: web
      port: 8095
      targetPort: web
    - name: devices
      port: 8097
      targetPort: devices
