apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-ngx-env
data:
  # Hosting
  PAPERLESS_BIND_ADDR: "0.0.0.0"
  PAPERLESS_PORT: "8000"
  PAPERLESS_DATA_DIR: "/data/data"
  PAPERLESS_MEDIA_ROOT: "/data/media"
  PAPERLESS_CONSUMPTION_DIR: "/data/consume"
  # Dependencies
  PAPERLESS_REDIS: "redis://redis:6379"
  PAPERLESS_DBENGINE: "postgres"
  # App specific
  PAPERLESS_URL: "https://paperless.golocal.dev"
  PAPERLESS_OCR_LANGUAGE: "deu"
  APERLESS_TIME_ZONE: "Europe/Berlin"

