apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless-ngx
resources:
  - namespace.yaml
  - redis
  - ../cloudnative-pg/cluster
  - volumes
  - paperless-ngx
labels:
  - pairs:
      app.kubernetes.io/name: paperless-ngx
    includeSelectors: true
    includeTemplates: true
patches:
  - target:
      kind: HelmRelease
      name: postgres-cluster
    patch: |
      - op: replace
        path: /spec/values/cluster/storage/storageClass
        value: "nfs-retain"