apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless-ngx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
spec:
  ingressClassName: dmz-ingress
  tls:
    - hosts:
        - paperless.golocal.dev
      secretName: paperless-ngx-tls
  rules:
    - host: paperless.golocal.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: paperless-ngx
                port:
                  name: paperless
