apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wyoming-protocol
resources:
  - namespace.yaml
  - piper
  - whisper
labels:
  - pairs:
      app.kubernetes.io/name: "wyoming-protocol"
    includeTemplates: true
