apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  selector: {}
  template:
    spec:
      containers:
        - image: docker.io/jellyfin/jellyfin:latest
          name: jellyfin
          imagePullPolicy: IfNotPresent
          env:
            - name: JELLYFIN_PublishedServerUrl
              value: "https://jellyfin.golocal.dev"
          ports:
            - containerPort: 8096
              protocol: TCP
            - containerPort: 7359
              protocol: UDP
          volumeMounts:
            - name: audio-books
              mountPath: /data/media/audio-books
              readOnly: True
            - name: movies
              mountPath: /data/media/movies
              readOnly: True
            - name: music
              mountPath: /data/media/music
              readOnly: True
            - name: shows
              mountPath: /data/media/shows
              readOnly: True
            - name: config
              mountPath: /config
            - name: cache
              mountPath: /cache
      restartPolicy: Always
      volumes:
        - name: audio-books
          persistentVolumeClaim:
            claimName: audio-books
        - name: movies
          persistentVolumeClaim:
            claimName: movies
        - name: music
          persistentVolumeClaim:
            claimName: music
        - name: shows
          persistentVolumeClaim:
            claimName: shows
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: cache
          emptyDir: {}