apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
spec:
  ingressClassName: dmz-ingress
  tls:
    - hosts:
        - jellyfin.golocal.dev
      secretName: jellyfin-tls
  rules:
    - host: jellyfin.golocal.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin
                port:
                  name: http
