apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin
resources:
  - namespace.yaml
  - pv.config.yaml
  - pvc.config.yaml
  - media
labels:
  - pairs:
      app.kubernetes.io/name: "jellyfin"
    includeSelectors: true
    includeTemplates: true
