apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      server: 10.0.0.21
      share: /mnt/data/csi/named
      subdir: jellyfin-config
    volumeHandle: 10.0.0.21#mnt/data/csi/named#jellyfin-config##
  mountOptions:
    - nfsvers=4.1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-named
  volumeMode: Filesystem
