apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-dmz
resources:
  - namespace.yaml
  - certificate.yaml
  - configmap.404.yaml
  - configmap.50x.yaml
  - helm-repository.yaml
  - helm-release.yaml
