apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - crd.yaml
  - cluster-role.yaml
  - service-account.yaml
  - cluster.role-binding.yaml
  - configmap.config.yaml
  - daemonset.yaml
labels:
  - pairs:
      tier: node
      app: multus
      name: multus
    includeSelectors: true
    includeTemplates: true
