---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - crdapplies.yaml
patches:
  - patch: |-
      - op: replace
        path: /spec/conversion/webhook/clientConfig/service/namespace
        value: metallb
    target:
      kind: CustomResourceDefinition
      name: bgppeers.metallb.io
