apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
  name: wireguard
spec:
  ingressClassName: dmz-ingress
  rules:
    - host: wireguard.golocal.dev
      http:
        paths:
          - backend:
              service:
                name: wg-easy-http
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - wireguard.local.dev
      secretName: wireguard-tls