apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wireguard
resources:
  - namespace.yaml
  - pvc.yaml
  - secret.pw.yaml
  - deployment.yaml
  - service.udp.yaml
  - service.ui.yaml
  - ingress.yaml
labels:
  - pairs:
      app.kubernetes.io/name: "wireguard-easy"
    includeSelectors: true
    includeTemplates: true
